version: '3.7'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./go:/go/src/github.com/juve534/nginx-lesson
        working_dir: /go/src/github.com/juve534/nginx-lesson
        ports:
            - 8088:80
            - 8080:8080
        depends_on:
            - php
        networks:
            - lesson_net
    php:
        image: php:7.4-fpm
        volumes:
            - ./:/workspace
        networks:
            - lesson_net
networks:
    lesson_net:
        driver: bridge