version: '3.7'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./go:/go/src/github.com/juve534/nginx-lesson
            - ./docker/init:/docker-entrypoint.d
        working_dir: /go/src/github.com/juve534/nginx-lesson
        ports:
            - 8088:80
            - 8080:8080
        depends_on:
            - php
        networks:
            - lesson_net
    php:
        image: php:7.4-fpm
        volumes:
            - ./php:/workspace
            - ./docker/phpfpm/php-fpm.conf:/usr/local/etc/php-fpm.d/php-fpm.conf
        networks:
            - lesson_net
networks:
    lesson_net:
        driver: bridge